### ISSUE TITLE
keyrings.alt tests rely on keyring tests

### ISSUE THREAD

**Issue by scarabeusiv** [jaraco/keyrings.alt#33]
Packages in general should not rely on tests in another package as most people are not really careful when messing around tests.
In this case tests are relying on following two files:

keyring/tests/test_backend.py
keyring/tests/util.py

Distributions usually just remove tests upon installation so they are not even available and this thus fails. Could you please rethink how to do that and rely only on the keyring api without the tests?

**Comment by frispete** [comment]
@scarabeusiv Hmm, sure, we can copy all dependent test files into all dependent projects, but since keyring is meant as a framework/infrastructure, changes in it, that results in adjusted/new test cases would have to be distributed manually to any dependent package. And you know the consequences of doing things manually...

What's wrong with my approach to package tests separately, instead of placing the burden on the developers and raising the danger of destabilizing dependent projects. 

https://build.opensuse.org/request/show/680759

This way, package installation is pure and clean, but dependent packages just use the new build requirement.

**Comment by jaraco** [comment]
> it makes sense to actually even revert the removal of the tests

Can you elaborate? What are you proposing?

**Comment by scarabeusiv** [comment]
This does not apply to the pip package, just our rpm. We basically prune all tests on install so only keyring modules stay but there are no tests available.

As such if this package or any other require keyring they will work but they won't find any test files which are used by the testsuite.

What is proposed by Hans-Peter is to create subpackage called keyrings-tests, which can be then pulled in by those using it. But in my view if you say that you want to keep using the tests as-is then it is better for us to revert the test removal in first place rather than to create any -test package.

**Comment by jaraco** [comment]
Oh. Revert the test removal during the RPM build. Yes, that's probably the best short-term solution.

I'm disinclined to create a shared package, like keyring-tests, but I might imagine that keyring could expose the testing fixtures in a module/package separate from the tests themselves. Imagine, for example, a `keyring.testing` module that would contain the test fixtures but not the tests. Then that code could be distributed with the package (and retained in RPMs), but the tests themselves could be removed.

**Comment by scarabeusiv** [comment]
Yea, fixutres as kerying.testing sound sensible as a long term solution. For now I will revert the keyring test removal and hopefully this will solve itself magically (well you will do it, but from distribution PoV ;-))
