### ISSUE TITLE
Improve docstrings to make it clear(er) how to parametrize any given keyring

### ISSUE THREAD

**Issue by yarikoptic** [jaraco/keyrings.alt#45]
e.g. looking at
```
In [5]: f.PlaintextKeyring?
Init signature: f.PlaintextKeyring()
Docstring:      Simple File Keyring with no encryption
File:           /usr/lib/python3/dist-packages/keyrings/alt/file.py
Type:           KeyringBackendMeta
Subclasses:    
```
it is absolutely not clear how to point it to a specific file "properly". Will go RTFM to see if there is a way besides the ugly way of looking into the code and doing 

```ipython
In [6]: kr = f.PlaintextKeyring(); kr.filename='/tmp/temp-keyring.txt'

In [7]: kr.set_password?
Signature: kr.set_password(service, username, password)
Docstring: Write the password in the file.
File:      /usr/lib/python3/dist-packages/keyrings/alt/file_base.py
Type:      method

In [8]: kr.set_password('theservice', 'user', 'password')


[1]  + 2527953 suspended  ipython3

$> cat /tmp/temp-keyring.txt 
[theservice]
user = 
	cGFzc3dvcmQ=
```

**Comment by jaraco** [comment]
I'm afraid I don't have any good advice here.

Generally speaking, keyring backends are meant to be zero-configuration. That is, they ideally just work out of the box with minimal configuration. That's because the primary use of keyring is as a user-facing CLI tool and as a library invocation with very limited get/set interfaces.

Taking a brief look at the implementation in file_base, it seems that both the file path and the file name are configurable in any given keyring, so that does give a programmer the ability to set those values programmatically, similar to how you've described.

Keyring does [solicit keyring properties from the environment](https://github.com/jaraco/keyring/blob/d1e37a5efb56ab4b805b721847c87fb94b9ca57b/keyring/backend.py#L142-L152) ([docs](https://github.com/jaraco/keyring/blob/main/README.rst#altering-keyring-behavior)), suggesting you could probably set KEYRING_PROPERTY_FILENAME, and that filename would be used in the keyring.

I'd welcome docstrings that would have made this easier. Please suggest a change. In the meantime, I'll close this issue as answered.
