### ISSUE TITLE
ImportError traceback on non-Windows

### ISSUE THREAD

**Issue by toyg** [jaraco/keyrings.alt#9]
Is there any way to suppress this ImportError traceback printout? It does not impact the actual import, but it pollutes logs. This is on Debian 8.4 (jessie), Py 3.4.2.

    >>> from keyrings.alt.file import EncryptedKeyring
    Error initializing plugin Windows (alt) = keyrings.alt.Windows.
    Traceback (most recent call last):
    File "/home/toyg/sites/skypebot_v2/env/lib/python3.4/site-packages/keyring/backend.py", line 155, in _load_plugins
      init_func = ep.load()
    File "/home/toyg/sites/skypebot_v2/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2291, in load
      return self.resolve()
    File "/home/toyg/sites/skypebot_v2/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2297, in resolve
      module = __import__(self.module_name, fromlist=['__name__'], level=0)
    File "/home/toyg/sites/skypebot_v2/env/lib/python3.4/site-packages/keyrings/alt/Windows.py", line 9, in <module>
      from . import file
    ImportError: cannot import name 'file'

**Comment by jaraco** [comment]
Thanks for the report.

Hmm. The problem is a circular import issue. The import of `keyrings.alt.file` is triggering an import of `keyring`, which is initializing the entry points, which is triggering an import of `keyrings.alt.Windows`, which is trying to import `keyrings.alt.file`... and failing because file is incomplete in being imported. Prior to the move of these deprecated backends to `keyrings.alt`, this wasn't an issue because the entry points would get loaded on the invocation of `import keyring`.

I suspect you can work around the issue by issuing `import keyring` before your import... though you shouldn't have to do that. It's not obvious to me what the solution is, though, so I'll have to circle back on this issue later.

**Comment by jaraco** [comment]
So I'm considering my options here.

### Late import file

I considered importing the `file` module later, perhaps after the module had a chance to load, but that's not possible, given that it's needed as a base class for the Windows backend.

### Remove the Windows backend

It may be that no one is using this deprecated backend, and maintaining it is just a waste. Hard to tell though without removing it and seeing who complains. If someone were to complain, we could always re-release this functionality as a separate package, meaning it could be excluded in environments where it's irrelevant and problemmatic (i.e. file backend is indicated explicitly).

### Extract common functionality into separate module

I'm not sure yet if it's possible, but I'm going to explore moving the common functionality into a separate module which would then be referenced separately by `file` and `Windows`, avoiding the circular import.

**Comment by jaraco** [comment]
This third option looks to be feasible and to be the cleanest approach.

**Comment by jaraco** [comment]
@toyg: Can you `pip install git+https://github.com/jaraco/keyrings.alt@36a25caa` and let me know if that version solves your issue?

**Comment by toyg** [comment]
Yeah that looks good! Thanks! (sorry for the late response)

**Comment by jaraco** [comment]
Great! Release is going out now as 1.3, expect it after the tests run.
